
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.dz
  resources:
  - helloapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dz
  resources:
  - helloapps/finalizers
  verbs:
  - update
- apiGroups:
  - apps.dz
  resources:
  - helloapps/status
  verbs:
  - get
  - patch
  - update
